#!/usr/bin/env sh
source ./tools/util.sh
curl `config notification.base`/v1/email/send/notifications \
-i -s -w "\n" \
-XPOST \
-H'Content-Type: application/json' \
-H'Accept: application/json' \
-H"Authorization: Bearer `authtoken`" \
-d'{"user_id":10000293, "mail_to":"jeremy.williams@pay2.jp", "mail_from":"notice@paypay-corp.co.jp", "mail_subject":"Test", "mail_body":"Test body", "mail_type":"TEXT"}' \
| ./tools/pretty_json.rb
